priorities:
  - name: "AccueillirClients"
    priority: 6
    precondition: ["?A onto:expect etre_accueilli."] # evenement d'activation
    entry_state:  # preconditions
      - ["Robot hasEmptyHand bool#true","Robot isInArea WelcomeArea"]
    variables: []

  - name: "InstallerLesClients"
    priority: 5
    precondition: ["?A onto:expect etre_assis."]
    entry_state:
      - ["Robot hasEmptyHand bool#true","Robot isInArea WelcomeArea"]
    variables: ["?T","?A"]

  - name: "PrendreCommande"
    priority: 4
    precondition: ["?A onto:expect commander"]
    entry_state:
      - ["Robot hasEmptyHand bool#true","?T hasArea ?A","Robot isInArea ?A"]
    variables: ["?T"]

  - name: "ServirEntree"
    priority: 3
    precondition: ["?A onto:expect etre_servi_de_l_entree"]
    entry_state:
      - ["Robot hasEmptyHand bool#true","Robot isInArea HatchArea"]
    variables: ["?T","?D"]
#
#  - name: "DebarasserTable"
#    priority: 2
#    precondition: ["?T onto:isA RestaurantTable","?T onto:hasDishes ?D","?D onto:hasStatus empty"]
#    entry_state:
#      - ["Robot hasEmptyHand bool#true","?T hasArea ?A","Robot isInArea ?A"]
#    variables: ["?T","?D"]
#
#  - name: "EncaisserClients"
#    priority: 1
#    precondition: ["?C onto:hasRole client","?C onto:hasStatus ready_to_pay"]
#    entry_state:
#      - ["Robot hasEmptyHand bool#true","Robot isInArea WelcomeArea"]
#    variables: ["?C","?O"]
#
#  - name: "NettoyerTable"
#    priority: 0
#    precondition: ["?T onto:isA RestaurantTable","?T onto:hasStatus dirty_table"]
#    entry_state:
#      - ["Robot hasEmptyHand bool#true","?T hasArea ?A","Robot isInArea ?A"]
#    variables: ["?T"]

  - name: "AL"
    priority: -1
    precondition: []
    entry_state:
      - ["Robot hasEmptyHand bool#true","Robot isInArea DinningArea"]
    variables: []
